version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    command: --replSet rs0  # <--- this startup command enables the replicaset.
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db